local-phone-apps := ApplicationsProvider \
		    Activation \
		    BackupRestoreConfirmation \
		    CameraTestApp \
		    CertInstaller \
		    CompatibilityMode \
		    DefaultContainerService \
		    DoubleTapWakeup \
		    DrmProvider \
		    FaceLock \
		    GnssAirTest \
		    GnssPosTest \
		    GnssTest \
		    HiddenMenu \
		    KeyChain \
		    LteConfigs \
		    LGBluetooth4 \
		    LGEIME_THEME_ZEEBLACK \
		    LGLiveWallpapersPicker \
		    LGSlideAside \
		    SystemUI_Provider \
		    LgNfc \
		    LGATCMDClient \
		    PermissionToAccessLgeApi \
		    PrefAct \
		    MediaUploader \
		    MediaProvider \
		    NetworkLocation \
		    QuicksetSDK \
		    SharedStorageBackup \
		    SplitWindowService \
		    SprintExtensionProvider \
		    SprintExtension_signed \
		    SprintHiddenMenu \
		    SprintID \
		    SprintSDM \
		    SprintTouch \
		    Sprint_Installer \
		    Stk \
		    TimeService \
		    UserDictionaryProvider \
		    VpnDialogs \
		    Vtt-Sprint \
		    WAPPushManager \
		    WapService \
		    WiseScreen \
		    WIFIOffloader \
		    Zone-Sprint \
		    com.qualcomm.location \
		    com.qualcomm.services.location \
		    qcrilmsgtunnel \
		    xtra_t_app